# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bf5b60a1540fe99db74d8f87e4862e2f039ef59339fdf9f9b403792597cd8dc5fcf732554de4222946d82d00d87ab66e78a203376f99e063828cfac57cf06e0

test:
  secret_key_base: 90e899d3ff4aa4b319df520d9fbe9acc6e9d913cffa4978451d510fdee518bce8481a5c10abff08d67f827a7a8543122c35adfb382907faf9f42929410907fc2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
